### ISSUE TITLE
Warning caused by wrong argument passed to pyright by the wrapper script

### ISSUE THREAD

**Issue by bustbr** [RobertCraigie/pyright-python#11]
Running the `pyright` bin installed from this module causes the following call to `npx`:

```sh
npx --silent --yes pyright@1.1.190
```

If an argument is present (e.g. `pyright foo`) this changes to:

```sh
npx --silent --yes pyright@1.1.190 -- foo
```

This causes the following warning from pyright:

```
File or directory "/Users/tim/repos/github.com/smb-ag/reels/--" does not exist.
```

This is because the `--` is passed from `npx` to `pyright` where it is not handled in the typical gnunix way and instead understood as the first "file" argument to pyright.
As per [npx docs](https://docs.npmjs.com/cli/v8/commands/npx) the correct call should be:
(using `npm exec -- <pkg>[@<version>] [args...]` syntax)

```sh
npx --silent --yes -- pyright@1.1.190 foo
```

**Comment by RobertCraigie** [comment]
What version of node are you using?

**Comment by bustbr** [comment]
> What version of node are you using?

$ node --version
v17.0.1

> Thank you for reporting this with such detail!

sure, thank you for providing this package! :)

**Comment by RobertCraigie** [comment]
Turns out that the fix for this issue actually causes the error on my machine.

**Comment by RobertCraigie** [comment]
Closing as I was wrong, I was using an old version.
