### ISSUE TITLE
"You do not have sufficient privilege to perform this operation."

### ISSUE THREAD

**Issue by bersbersbers** [RobertCraigie/pyright-python#111]
Calling `pyright`, I get

>  * Install prebuilt node (18.11.0) ..... done.
You do not have sufficient privilege to perform this operation.
You do not have sufficient privilege to perform this operation.
Error: Failed to create nodejs.exe link
...

See also https://github.com/microsoft/pyright/issues/3553

**Comment by RobertCraigie** [comment]
Thanks for the report and sorry for the very long delay in responding.

I'm going to close this as the next release will add [`nodejs-wheel`](https://pypi.org/project/nodejs-wheel-binaries/) as an alternative to `nodeenv` which should be more reliable.

You can try it out today with
```
python -m pip install 'git+https://github.com/RobertCraigie/pyright-python.git#egg=pyright[nodejs]'
```
When released, it will be
```
pip install pyright[nodejs]
```
Please let me know if you run into any issues with this new setup.
