### ISSUE TITLE
Unable to run pyright pre-commit under VPN

### ISSUE THREAD

**Issue by Mayankm96** [RobertCraigie/pyright-python#143]
Thanks a lot for the nice integration. 

I am facing a strange issue when integrating pyright pre-commit with my repository. Everything works fine when I am not using a company VPN. However, as soon as I activate it, the check gets hung with a blinking cursor:

```
$ pre-commit run --all-files
black....................................................................Passed
flake8...................................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
isort (python)...........................................................Passed
pyupgrade................................................................Passed
pyright..................................................................
```

**Comment by RobertCraigie** [comment]
@Mayankm96 does your company VPN disallow [npm](https://www.npmjs.com/)?

**Comment by RobertCraigie** [comment]
Thanks for the report, I'm going to close this in favour of #231 as that will avoid any runtime downloads.
