### ISSUE TITLE
pyright-langserver does not start if username contains an `@` symbol

### ISSUE THREAD

**Issue by denisw** [RobertCraigie/pyright-python#146]
On my work laptop (macOS), my username is my email address. When I install the `pyright` PyPI package and try to run `pyright-langserver`, I get the following error (I replace the original email address with `name@example.com`):

```
npm ERR! Invalid name: "pyright-python-langserver.name@example.com"
```

The issue seems to be that `langserver.py` includes the return value of [`getpass.getuser()`](https://docs.python.org/3/library/getpass.html#getpass.getuser)) in the name of a temporarily generated NPM package. As `@` is not a valid character for an NPM package name, the above error occurs.

**To reproduce:** Set `LOGNAME` to a username with an `@` character.

```sh
# This fails:
LOGNAME=alice@example.com pyright-langserver --stdio
 
# This works as expected:
LOGNAME=alice pyright-langserver --stdio
```

**Possible fix:** Remove or replace special characters in usernames before constructing the temporary NPM package name, or do not rely on the username at all, e.g. by using a random suffix.

**Comment by RobertCraigie** [comment]
Thanks for the bug report and the detailed reproduction steps and suggested fix!

The solution I decided to go with is to hash the result of `getpass.getuser()` instead of attempting to strip special characters.

This will be fixed in the next release.

**Comment by denisw** [comment]
Wow, that was quick - thanks for the fix!
