### ISSUE TITLE
pyright-langserver wrapper produces extraneous output

### ISSUE THREAD

**Issue by ndryden** [RobertCraigie/pyright-python#149]
Running the `pyright-langserver` wrapper produces extraneous, non-JSONRPC output to stdout:
```
$ pyright-langserver --stdio 2> /dev/null                                                     
Wrote to /tmp/ndryden/pyright-python-langserver.1602085020987684455/package.json:

{
  "name": "pyright-python-langserver.1602085020987684455",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
Content-Length: 119

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Pyright language server 1.1.293 starting"}}Content-Length: 187

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Server root directory: /tmp/ndryden/pyright-python-langserver.1602085020987684455/node_modules/pyright/dist/"}}
```

This appears to have been introduced in release v1.1.291, as v1.1.290 does not exhibit this. In particular, this breaks eglot, the LSP interface in emacs (see discussion [here](https://github.com/joaotavora/eglot/discussions/1166#discussioncomment-4941259)).

It looks like this output comes from the added `npm init` call in 04f1508.

A simple fix would be to suppress the output of that by adding `stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL` to the `node.run` call. If this seems reasonable, I can PR it.

**Comment by RobertCraigie** [comment]
Ah sorry about this. Your proposed solution sounds good to me.

**Comment by ndryden** [comment]
No worries. :) PR made.
