### ISSUE TITLE
fsevents not installed on MacOS

### ISSUE THREAD

**Issue by adampauls** [RobertCraigie/pyright-python#191]
Main issue [here](https://github.com/microsoft/pyright/issues/5415). If I set `export CHOKIDAR_PRINT_FSEVENTS_REQUIRE_ERROR=1` and run `pyright -w`, I see
```
Error: Cannot find module 'fsevents'
Require stack:
- /Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js
- /Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 4943 (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:84)
    at i (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:816)
    at 5047 (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/vendor.js:2:464020)
    at i (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:816)
    at 8590 (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/vendor.js:2:451691)
    at i (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:816) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js',
    '/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/index.js'
  ]
}
```

I'm using pyright 1.1.316. If I manually run `npm install fsevents` in the `$HOME/.cache/pyright-python/1.1.316` directory, then the error goes away.

**Comment by Glawill** [comment]
> Main issue [here](https://github.com/microsoft/pyright/issues/5415). If I set `export CHOKIDAR_PRINT_FSEVENTS_REQUIRE_ERROR=1` and run `pyright -w`, I see
> 
> ```
> Error: Cannot find module 'fsevents'
> Require stack:
> - /Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js
> - /Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/index.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
>     at Module._load (node:internal/modules/cjs/loader:920:27)
>     at Module.require (node:internal/modules/cjs/loader:1141:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at 4943 (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:84)
>     at i (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:816)
>     at 5047 (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/vendor.js:2:464020)
>     at i (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:816)
>     at 8590 (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/vendor.js:2:451691)
>     at i (/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js:1:816) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/dist/pyright.js',
>     '/Users/adpauls/.cache/pyright-python/1.1.316/node_modules/pyright/index.js'
>   ]
> }
> ```
> 
> I'm using pyright 1.1.316. If I manually run `npm install fsevents` in the `$HOME/.cache/pyright-python/1.1.316` directory, then the error goes away.

why i always push to git it gives me an error

**Comment by adampauls** [comment]
Fixed by https://github.com/microsoft/pyright/pull/5503.
