### ISSUE TITLE
use different venv during local development and during cicd

### ISSUE THREAD

**Issue by copdips** [RobertCraigie/pyright-python#214]
Hello,

I'm using pyright by is public github action. and I see that pyright has a param `venv` which can specify the venv path, I would like to know that, during the local development, I use venv, it's OK. But during the CICD, I don't use venv, just install everything at system level, in such case, how to keep a single `pyproject.toml` but with different venv ?
Does pyright support find automatically the package installation path based on python executable used.
It seems that mypy can do that, we do not need to specify which venv to use, just run `mypy`

**Comment by ryanpeach** [comment]
Same

**Comment by RobertCraigie** [comment]
For most use cases you shouldn't need to explicitly specify a virtual environment path, you can instead activate your environment before running `pyright` and it will be picked up automatically.

**Comment by copdips** [comment]
> For most use cases you shouldn't need to explicitly specify a virtual environment path, you can instead activate your environment before running `pyright` and it will be picked up automatically.

Hello @RobertCraigie 

Thank you for taking time to reply to this issue.
But I think there might be a misunderstanding here.
The reason why I raise this issue was just because pyright installed from repo cannot pick up automatically the venv, and you've given the workaround by guiding us to use the venv param in the pyproject.toml file.

Hereunder the guideline in the `README.md`:

![image](https://github.com/user-attachments/assets/0d07886c-c10c-435c-bd2b-498fc99f6499)

**Comment by copdips** [comment]
And the reason I use Pyright installed from the repository and not from `pip install pyright` is that sometimes [Pyright doesn't work due to a 'file not found' error](https://github.com/RobertCraigie/pyright-python/issues/213)."

**Comment by RobertCraigie** [comment]
Ah I see, you're specifically talking about pre-commit. Sorry for the misunderstanding.

I'm not sure if there's a great solution here unfortunately, I'm also not familiar with pre-commit anymore as I stopped using it years ago.

Would adding your dependencies to the pre-commit config work for you? https://pre-commit.com/#config-additional_dependencies

**Comment by RobertCraigie** [comment]
ah @copdips maybe this would be helpful? https://github.com/RobertCraigie/pyright-python/issues/203#issuecomment-1706832522

**Comment by copdips** [comment]
> adding your dependencies

adding deps in pyright pre-commit conf requires us to declare them in 2 places, which I don't feel confortable with...

**Comment by copdips** [comment]
> ah @copdips maybe this would be helpful? [#203 (comment)](https://github.com/RobertCraigie/pyright-python/issues/203#issuecomment-1706832522)

Thanks a lot, I didn't know pyright also has `--pythonpath` parameter.
This will definitely help, I will try using `sys.executable` first instead of `os.path.realpath(sys.executable)`, as `realpath` reflects the system-level Python path, but not the one in `venv`.

**Comment by RobertCraigie** [comment]
> adding deps in pyright pre-commit conf requires us to declare them in 2 places, which I don't feel confortable with...

oh there's no way to specify a `requirements.txt` or similar with pre-commit? would probably be worth filing a feature request with pre-commit if there isn't an existing one already
