### ISSUE TITLE
Consider pinning the internal pyright version and auto-releasing new pyright-python versions

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/pyright-python#23]
## Problem

Our current solution does not work well with CI.

CI runs should be reproducible, however when using our wrapper, a CI run could seemingly randomly fail due to bug fixes / changes in pyright's type checking in a new release. This makes people set `PYRIGHT_PYTHON_FORCE_VERSION` and then never update it, causing the issue that Eric originally wanted to avoid.

## Solution

We should create a GitHub action workflow that will run regularly, checking if there is a new pyright version available. When a new version is detected, the workflow should then:

- update the internal pyright version to it's latest
- bump our version
- create a PR
- merge once checks pass
- publish a new release to PyPi

Users that have a solution like Dependabot enabled will then receive a notification that there is a new pyright version available.  #22 would also help people keep their pyright version up to date.

However, some users might not want to have to manually update their pyright-python version every time a new pyright version is released, we should also provide an escape hatch to keep the old behaviour.

## Additional context

https://github.com/hikari-py/hikari/blob/965d6e8a4c7685a7b6d9fd1b53cec3609f0821e3/pipelines/config.py#L40

**Comment by artificial-aidan** [comment]
@RobertCraigie we are interested in experimenting with the proposed solution. And would be willing to try and tackle the github workflows. A few questions.

1. How would you want to see the internal version stored. My first thought was to put it next to the pyright version in `__init__.py` and then use it as a default if the environment variable check for forced version.
2. As far as an escape hatch for the old behavior, how about detecting the `PYRIGHT_PYTHON_FORCE_VERSION` environment variable being set to `latest`, and then just getting the latest pyright version.

**Comment by RobertCraigie** [comment]
Thanks @artificial-aidan! Both of your proposed solutions sound good.

@erictraut is this an acceptable solution?

**Comment by erictraut** [comment]
Yeah, that sounds good to me. Thanks for asking.

**Comment by artificial-aidan** [comment]
Something else to consider. Should the python package version match the pyright npm version? Seems like if were going to be keeping in sync, maybe they should just be the same version number?

**Comment by RobertCraigie** [comment]
@artificial-aidan Yes I had considered that but I'm not sure what version numbers the python package should use. For example, how would we publish patches? Maybe we don't need to because pyright is updated so often it could just be included in the next release?

**Comment by artificial-aidan** [comment]
Ah i see what you mean. You could use a [post release](https://www.python.org/dev/peps/pep-0440/#id26)

**Comment by RobertCraigie** [comment]
That is a good suggestion, I had not heard of post releases before.

**Comment by artificial-aidan** [comment]
Neither had I, just went browsing on the PEP.

I guess all that would have to change would be the regex's for version finding. Otherwise it could go in right now that way.

**Comment by RobertCraigie** [comment]
Implemented in #24
