### ISSUE TITLE
Prebuilt node install fails - v22.0.0 not found

### ISSUE THREAD

**Issue by monkpit** [RobertCraigie/pyright-python#267]
Moved from https://github.com/microsoft/pyright/issues/7762

Using pyright v1.1.360 has started failing for me today in my CI pipeline with the following error:

 `* Install prebuilt node (22.0.0) .Failed to download from https://unofficial-builds.nodejs.org/download/release/v22.0.0/node-v22.0.0-linux-x64-musl.tar.gz`
When I follow the link, it indeed does not exist. It looks like this version of node was [released today](https://nodejs.org/en/about/previous-releases)

I am caching pyright in a private repository to avoid issues like this, but I can't avoid this one since it seems to be done at runtime.

For reference, the command in my CI environment is: `pyright . --venvpath <path>`, and pyright is installed in a previous step using `poetry`.

Can anyone reproduce this? Are there any workarounds? Can I override the version of node that pyright is asking for via a flag?

EDIT: My current workaround was to add `node` to my CI build docker image, which is good enough for me, for now.

**Comment by monkpit** [comment]
Reopening this issue since it’s happening again today with 22.3.0, and should be resolved so this doesn’t crop up again with each node release.

**Comment by RobertCraigie** [comment]
I'm going to close this issue as the next release will add [`nodejs-wheel`](https://pypi.org/project/nodejs-wheel-binaries/) as an alternative to `nodeenv` which should be more reliable.

You can try it out today with
```
python -m pip install 'git+https://github.com/RobertCraigie/pyright-python.git#egg=pyright[nodejs]'
```
When released, it will be
```
pip install pyright[nodejs]
```
Please let me know if you run into any issues with this new setup.
