### ISSUE TITLE
Add LSP support

### ISSUE THREAD

**Issue by zaid-g** [RobertCraigie/pyright-python#7]
Currently trying to use this pyright install with nvim's native LSP support based on [this configuration](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#pyright), but the default `cmd` value (`cmd = { "pyright-langserver", "--stdio" }`) doesn't exist and is not installed by installing this package. Modifying the default value to just `pyright` i.e. `cmd = { "pyright"},` doesn't work.

I can't find where documentation on the executable `pyright-langserver`

**Comment by RobertCraigie** [comment]
Just setting the command to `pyright` won't work as the language server does not come bundled with the CLI as far as I am aware.

I do think we might be able to add support for this though as the language server is still installed along with the pyright npm module.

**Comment by RobertCraigie** [comment]
Looking into this, the most difficult part is actually resolving the location of the installed pyright npm package

**Comment by RobertCraigie** [comment]
@zaid-g This has been added in `v0.0.11`, please try it out and let me know if you encounter any issues!
