### ISSUE TITLE
LSP Error lanunching pyright-langserver

### ISSUE THREAD

**Issue by baco** [RobertCraigie/pyright-python#71]
Launching the server entrypoint (`pyright-langserver`) as an editor would launch it (Neovim with native LSP support in my case), when trying to get LSP live information results in the following error:

```
$ pyright-langserver --stdio

up to date, audited 203 packages in 2s

found 0 vulnerabilities
Traceback (most recent call last):
  File "/tmp/.venv/bin/pyright-langserver", line 8, in <module>
    sys.exit(entrypoint())
  File "/tmp/.venv/lib/python3.10/site-packages/pyright/langserver.py", line 57, in entrypoint
    sys.exit(main(*sys.argv[1:]))
  File "/tmp/.venv/lib/python3.10/site-packages/pyright/langserver.py", line 26, in main
    return run(*args, **kwargs).returncode
  File "/tmp/.venv/lib/python3.10/site-packages/pyright/langserver.py", line 51, in run
    raise RuntimeError(f'Expected language server entrypoint: {binary} to exist')
RuntimeError: Expected language server entrypoint: /tmp/pyright-python-langserver.baco/node_modules/pyright/langserver.index.js to exist
```

**Comment by RobertCraigie** [comment]
Interesting, what are the contents of the `/tmp/pyright-python-langserver.baco/node_modules/pyright/` directory?

**Comment by baco** [comment]
`/tmp/pyright-python-langserver.baco/` was completly empty, no `node_modules` nor any other file in it. But... after yesterday's release now seems to be working. Let me try it a bit more and tell you if the bug needs closing.

**Comment by baco** [comment]
Couldn't reproduce it. The issue solved itself after some updates of the `pyright` library.
