### ISSUE TITLE
Warning - file or directory -- does not exist

### ISSUE THREAD

**Issue by asears** [RobertCraigie/pyright-python#9]
See https://github.com/microsoft/pyright/issues/2527

Describe the bug

Getting a warning about file or directory -- does not exist.

[tool.pyright]
stubPath = ""  # typings by default shows warning
exclude = ["**/node_modules",
    "**/__pycache__"
]
ignore = ["source/","build/"]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.8.5"
pythonPlatform = "Linux"
Searching for source files
File or directory "C:\myprojectfolder\--" does not exist.
Found 21 source files
VS Code extension or command-line

Command line. Pyright 0.0.11

**Comment by RobertCraigie** [comment]
Do you have node installed?

**Comment by RobertCraigie** [comment]
@asears Could you try installing from this branch and see if that resolves your issue please.

```
pip install -U git+https://github.com/RobertCraigie/pyright-python@fix/arg-separator
```

**Comment by asears** [comment]
That resolves the issue, thanks!  

In case you need them.

```shell
node --version
v13.11.0
```

The environment variable didn't seem to do much on Windows and output is just standard pyright .  output.
