### ISSUE TITLE
Conflicting documentation on which pyright version is used by default

### ISSUE THREAD

**Issue by Avasam** [RobertCraigie/pyright-python#95]
> We also automatically upgrade the pyright npm package to its latest version on every run, see below for how to change this behaviour.

and

> By default Pyright for Python is set to target a specific pyright version and new releases will be automatically created whenever a new pyright version is released. [...] If you would rather not have to update your installation every time a new pyright release is created then you can automatically use the latest available pyright version by setting the environment variable PYRIGHT_PYTHON_FORCE_VERSION to latest.

So which one is it? Automatically updated or do I need to configure to use `latest`?

**Comment by RobertCraigie** [comment]
Hey, sorry about this documentation mismatch. We no longer automatically update by default. https://github.com/RobertCraigie/pyright-python/issues/117#issuecomment-1295862258.

The incorrect docs have been removed.
